# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # NuGet dependencies
  - package-ecosystem: "nuget"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/src/frontend/csrs-portal"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
