version: "3.8"

services:
  # #############################################################################################
  # ###                                 Csrs FRONTEND                                         ###
  # #############################################################################################
  jag-csrs-frontend:
    container_name: jag-csrs-frontend
    build:
      context: ./src/frontend/csrs-portal
    restart: always
    ports:
      - "8080:8080"
    ## following is used for testing nginx.conf locally. No need to build the csrs-portal every
    ## time we change the nginx.conf
    #volumes:
    #  - ./src/frontend/csrs-portal/nginx.conf:/opt/app-root/etc/nginx.default.d/default.conf
    depends_on: [jag-csrs-api, keycloak]

  # #############################################################################################
  # ###                                 Csrs BACKEND                                          ###
  # #############################################################################################
  jag-csrs-api:
    container_name: jag-csrs-api
    build:
      context: ./src/backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - SERILOG__WRITETO__1__NAME=Seq
      - SERILOG__WRITETO__1__ARGS__SERVERURL=http://seq:5341
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans
      - FILEMANAGER__ADDRESS=https://localhost:8084
      - FILEMANAGER__SECURE=true
    ports:
      - "8081:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on: [seq, zipkin]

  # ------------------------------------------------------------------------------
  # jag-csrs-file-manager
  # 
  # ------------------------------------------------------------------------------
  jag-csrs-file-manager:
    container_name: jag-csrs-file-manager
    build:
      context: ./src/backend
      dockerfile: Csrs.Services.FileManager/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:8080
    ports:
      - "8084:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  #############################################################################################
  ###                                  KEYCLOAK                                             ###
  #############################################################################################
  keycloak:
    container_name: csrs-keycloak
    image: quay.io/keycloak/keycloak
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_FRONTEND_URL: http://localhost:8082/auth
    volumes:
      - ./infrastructure/keycloak/realm-export.json:/tmp/realm-export.json
    ports:
      - 8082:8080

  # #############################################################################################
  # ###                                  KEYCLOAK CONFIG                                      ###
  # #############################################################################################
  keycloak-config:
    container_name: csrs-keycloak-config
    build:
      context: ./infrastructure/keycloak
      args:
        - KEYCLOAK_URL=http://keycloak:8080
    command: sh -c "dockerize -wait http://keycloak:8080 -timeout 300s /tmp/createuser.sh"
    depends_on: [keycloak]

  # #############################################################################################
  # ###                                  SEQ CONFIG                                           ###
  # #############################################################################################
  seq:
    container_name: csrs-seq
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341   # logs are written here, do not need to expose, but will so we can log from outside
      - 8083:80     # user interface is available here

  # #############################################################################################
  # ###                                  ZIPKIN CONFIG                                        ###
  # #############################################################################################
  zipkin:
    container_name: csrs-zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411

# #############################################################################################
# ###                                  NETWORK CONFIG                                       ###
# #############################################################################################

networks:
  csrs-net:
    driver: "bridge"
